const GET_DATA_REQUEST = "GET_DATA_REQUEST";
const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
const GET_DATA_FAILURE = "GET_DATA_FAILURE";

const ADD_DATA_REQUEST = "ADD_DATA_REQUEST";
const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
const ADD_DATA_FAILURE = "ADD_DATA_FAILURE";



export {
  GET_DATA_FAILURE,
  GET_DATA_REQUEST,
  GET_DATA_SUCCESS,
  
  ADD_DATA_FAILURE,
  ADD_DATA_REQUEST,
  ADD_DATA_SUCCESS,
  
};
